services:
  backend:
    build:
      context: .
      dockerfile: cooperMAS/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
